---
title: "Informe Global Arriendos"
author: "Estefania Echeverry Franco"
date: '2022-09-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Librerias
library(knitr)
```

```{r}
library(readxl)
Colores <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 1)
Calasanz <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 2)
Laureles <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 3)
Poblado <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 4)
Sabaneta <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 5)
Estrella <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 6)
Envigado <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 7)
Bello <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 10)
No_se <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 8)
No_se_1 <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 9)
Global_Sedes <- read_excel("informe Global ARRIENDOS.xlsx",col_names = TRUE,sheet = 11)
```
```{r}
# Centro de Costos Colores

uno <- c(1:7,10:13)
Colores2018 <- kable(Colores[uno,1:14 ], caption = "2018 Colores",col.names= NULL)
Colores2018

dos <- c(16:24,26:35)
Colores2019 <- kable(Colores[dos,1:15 ], caption = "2019 Colores",col.names= NULL)
Colores2019

Colores2020 <- kable(Colores[39:51,1:17 ], caption = "2020 Colores",col.names= NULL)
Colores2020

Colores2021 <- kable(Colores[55:84,1:16 ], caption = "2021 Colores",col.names= NULL)
Colores2021

Colores2022 <- kable(Colores[87:104,1:15 ], caption = "2022 Colores",col.names= NULL)
Colores2022
```

```{r}
# Centro de Costos Calasanz

Calasanz2022 <- kable(Calasanz[1:8,1:15 ], caption = "2022 Colores")
Calasanz2022

```
```{r}
# Centro de Costos Laureles

tres <- c(2:6,9:12)
Laureles2018 <- kable(Laureles[tres,1:15 ], caption = "2018 Colores",col.names= Laureles[1,1:15])
Laureles2018
cuatro <- c(16:20,23:28)
Laureles2019 <- kable(Laureles[cuatro,1:16 ], caption = "2019 Colores",col.names= Laureles[15,1:16])
Laureles2019
Laureles2020 <- kable(Laureles[47:55,1:15 ], caption = "2020 Colores",col.names= NULL)
Laureles2020
quinto <- c(59:65,68:75)
Laureles2021 <- kable(Laureles[quinto,1:15 ], caption = "2021 Colores",col.names= NULL)
Laureles2021
Laureles2018 <- kable(Laureles[uno,1:15 ], caption = "2018 Colores",col.names= NULL)
Laureles2018
```

